  
--##++[[ProductType]]
CREATE TABLE TB_HTMS_PRODUCTTYPE(
	TYPEID INTEGER  not null,
	TYPENAME VARCHAR(100)  not null,
	TYPECODE VARCHAR(100)  not null,
	TYPEDESC VARCHAR(300),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_PRODUCTTYPE primary key (TYPEID)
);
--##--[[ProductType]]

  
--##++[[Product]]
CREATE TABLE TB_HTMS_PRODUCT(
	PRODUCTID INTEGER  not null,
	TYPEID INTEGER,
	PRODUCTNAME VARCHAR(100),
	PRODUCTCODE VARCHAR(100),
	PRODUCTDESC VARCHAR(300),
	SAPNO VARCHAR(100),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_PRODUCT primary key (PRODUCTID)
);
--##--[[Product]]

  
--##++[[Factory]]
CREATE TABLE TB_HTMS_FACTORY(
	FACTORYID INTEGER  not null,
	FACTORYNAME VARCHAR(100),
	FACTORYCODE VARCHAR(100),
	FACTORYDESC VARCHAR(1000),
	FACTORYADDRESS VARCHAR(300),
	FACTORYCONTACTOR VARCHAR(30),
	FACTORYTELPHONE VARCHAR(30),
	ISVLIDATE INTEGER default '1',
	constraint PK_TB_HTMS_FACTORY primary key (FACTORYID)
);
--##--[[Factory]]

  
--##++[[Route]]
CREATE TABLE TB_HTMS_ROUTE(
	ROUTEID INTEGER  not null,
	FACTORYID INTEGER,
	AREAID INTEGER,
	PRODUCTID INTEGER,
	CREATOR INTEGER,
	CREATETIME VARCHAR(30),
	MODIFIER INTEGER,
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_ROUTE primary key (ROUTEID)
);
--##--[[Route]]

  
--##++[[Area]]
CREATE TABLE TB_HTMS_AREA(
	AREAID INTEGER  not null,
	PARENTAREAID INTEGER,
	AREACODE VARCHAR(10),
	AREANAME VARCHAR(100),
	AREALEVEL INTEGER,
	AREAROUTE VARCHAR(100),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_AREA primary key (AREAID)
);
--##--[[Area]]

  
--##++[[CustomerAddr]]
CREATE TABLE TB_HTMS_CUSTOMERADDR(
	CADDRID INTEGER  not null,
	CUSTOMERID INTEGER,
	CADDRDETAIL VARCHAR(30),
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_CUSTOMERADDR primary key (CADDRID)
);
--##--[[CustomerAddr]]

  
--##++[[TransPrice]]
CREATE TABLE TB_HTMS_TRANSPRICE(
	PRICEID INTEGER  not null,
	ROUTEID INTEGER,
	PRICETYPE INTEGER,
	CUSTOMERPRICE VARCHAR(30),
	COMPANYPRICE VARCHAR(30),
	CARRIERPRICE VARCHAR(30),
	PRICESTART VARCHAR(30),
	PRICEEND VARCHAR(30),
	PRICEUNIT VARCHAR(30),
	CREATOR VARCHAR(30),
	CREATETIME INTEGER,
	MODIFIER VARCHAR(30),
	MODIFYTIME INTEGER,
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_TRANSPRICE primary key (PRICEID)
);
--##--[[TransPrice]]

  
--##++[[Customer]]
CREATE TABLE TB_HTMS_CUSTOMER(
	CUSTOMERID INTEGER  not null,
	CUSTOMERCODE VARCHAR(100),
	CUSTOMERNAME VARCHAR(100),
	CUSTOMERNOTICE VARCHAR(300),
	CUSTOMERAMOUNT VARCHAR(30),
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_CUSTOMER primary key (CUSTOMERID)
);
--##--[[Customer]]

  
--##++[[SendDetail]]
CREATE TABLE TB_HTMS_SENDDETAIL(
	SENDDETAILID INTEGER  not null,
	SENDID INTEGER,
	TRANSDETAILID INTEGER,
	TRANSPORTID INTEGER,
	TRANSFERID INTEGER,
	SHIPDETAILID INTEGER,
	CODETAILID INTEGER,
	SHIPID INTEGER,
	CADDRID INTEGER,
	PRODUCTID INTEGER,
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	FETCHTONNUM VARCHAR(30),
	FETCHPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTULFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	USEFREIGHT VARCHAR(30),
	TRANSDETAILNOTICE VARCHAR(300),
	TRANSDETAILSTATUS VARCHAR(30),
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_SENDDETAIL primary key (SENDDETAILID)
);
--##--[[SendDetail]]

  
--##++[[CustOrder]]
CREATE TABLE TB_HTMS_CUSTORDER(
	CORDERID INTEGER  not null,
	CUSTOMERID INTEGER,
	CORDERNAME VARCHAR(30),
	CORDERCODE VARCHAR(30),
	CUSTOMERCODE VARCHAR(30),
	SALENUM VARCHAR(30),
	SALECHANNEL VARCHAR(30),
	PRODUCTGROUP VARCHAR(30),
	SALEGROUP VARCHAR(30),
	SALEDEPARTMENT VARCHAR(30),
	SALETYPE VARCHAR(30),
	EXCHANGETITLE VARCHAR(30),
	FETCHFACTORY VARCHAR(300),
	DELIVERYSTATUS INTEGER,
	CREATEDATE VARCHAR(30),
	CRECATETIME VARCHAR(30),
	CREATOR VARCHAR(30),
	INPUTTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_CUSTORDER primary key (CORDERID)
);
--##--[[CustOrder]]

  
--##++[[TransportDetail]]
CREATE TABLE TB_HTMS_TRANSPORTDETAIL(
	SENDDETAILID INTEGER  not null,
	TRANSDETAILID INTEGER,
	TRANSPORTID INTEGER,
	TRANSFERID INTEGER,
	SHIPDETAILID INTEGER,
	CODETAILID INTEGER,
	SHIPID INTEGER,
	CADDRID INTEGER,
	PRODUCTID INTEGER,
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	FETCHTONNUM VARCHAR(30),
	FETCHPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTULFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	TRANSDETAILNOTICE VARCHAR(30),
	TRANSDETAILSTATUS INTEGER,
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER,
	constraint PK_TB_HTMS_TRANSPORTDETAIL primary key (SENDDETAILID)
);
--##--[[TransportDetail]]

  
--##++[[Ship]]
CREATE TABLE TB_HTMS_SHIP(
	SHIPID INTEGER  not null,
	CORDERID INTEGER,
	CUSTOMERID INTEGER,
	SHIPCODE VARCHAR(30),
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	ACTUALTONNUM VARCHAR(30),
	ACTUALPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTUALFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	SHIPNOTICE VARCHAR(300),
	APPLIER INTEGER,
	APPLYTIME VARCHAR(30),
	APPLYSTATUS INTEGER,
	APPROVER VARCHAR(30),
	APPROVETIME VARCHAR(30),
	APPROVENOTICE VARCHAR(300),
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_SHIP primary key (SHIPID)
);
--##--[[Ship]]

  
--##++[[Send]]
CREATE TABLE TB_HTMS_SEND(
	SENDID INTEGER  not null,
	TRANSPORTID INTEGER,
	VEHICLEID INTEGER,
	DRIVERID INTEGER,
	CARRIERID INTEGER,
	TRANSID INTEGER,
	SENDCODE VARCHAR(30),
	PLANTIME VARCHAR(30),
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	ACTAULTONNUM VARCHAR(30),
	ACTAULPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTAULFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	SENDSTATUS INTEGER,
	SIGNPROOF VARCHAR(300),
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_SEND primary key (SENDID)
);
--##--[[Send]]

  
--##++[[CustOrderDetail]]
CREATE TABLE TB_HTMS_CUSTORDERDETAIL(
	CODETAILID INTEGER  not null,
	CORDERID INTEGER,
	CODETAILCERTIFICATE VARCHAR(100),
	METERIALNO VARCHAR(100),
	METERIALID INTEGER,
	CODETAILCERTIFICATEDESC VARCHAR(100),
	ORDERAMOUNT VARCHAR(30),
	ORDERUNIT VARCHAR(100),
	PROJECTVOLUME VARCHAR(30),
	VOLUMEUNIT VARCHAR(100),
	CONDITIONSUTOTAL VARCHAR(30),
	FREIGHT VARCHAR(30),
	UNITPRICE VARCHAR(30),
	DOCCONDCOUNT VARCHAR(30),
	ALREADYGETNUM VARCHAR(30),
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_CUSTORDERDETAIL primary key (CODETAILID)
);
--##--[[CustOrderDetail]]

  
--##++[[Transport]]
CREATE TABLE TB_HTMS_TRANSPORT(
	TRANSPORTID INTEGER  not null,
	CARRIERID INTEGER,
	TRANSID INTEGER,
	TRANSPORTCODE VARCHAR(30),
	PLANTIME VARCHAR(30),
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	ACTAULTONNUM VARCHAR(30),
	ACTAULPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTAULFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	TRANSPORTSTATUS VARCHAR(30),
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_TRANSPORT primary key (TRANSPORTID)
);
--##--[[Transport]]

  
--##++[[Vehicle]]
CREATE TABLE TB_HTMS_VEHICLE(
	VEHICLEID INTEGER  not null,
	CARRIERID INTEGER,
	VEHICLECODE VARCHAR(30),
	VEHICLENO VARCHAR(12),
	VEHICLEMAXTON VARCHAR(30),
	VEHICLELENGTH VARCHAR(30),
	VEHICLEWIDTH VARCHAR(30),
	VEHICLEHEIGHT VARCHAR(30),
	VEHICLEPERSONNUM INTEGER,
	VEHICLEDESC VARCHAR(300),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_VEHICLE primary key (VEHICLEID)
);
--##--[[Vehicle]]

  
--##++[[Driver]]
CREATE TABLE TB_HTMS_DRIVER(
	DRIVERID INTEGER  not null,
	CARRIERID INTEGER,
	DRIVERCODE VARCHAR(30),
	DRIVERNAME VARCHAR(30),
	DRIVERSEX INTEGER,
	DRIVERYEAR INTEGER,
	DRIVERIDNUM VARCHAR(30),
	DRIVERADDRESS VARCHAR(30),
	DRIVERMOBILE VARCHAR(30),
	DRIVERWEIXIN VARCHAR(30),
	DRIVERNOTICE VARCHAR(300),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_DRIVER primary key (DRIVERID)
);
--##--[[Driver]]

  
--##++[[Carrier]]
CREATE TABLE TB_HTMS_CARRIER(
	CARRIERID INTEGER  not null,
	CARRIERNAME VARCHAR(100),
	CARRIERCODE VARCHAR(100),
	CARRIERAREA VARCHAR(1000),
	CARRIERCONTACTOR VARCHAR(100),
	CARRIERTELEPHONE VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_CARRIER primary key (CARRIERID)
);
--##--[[Carrier]]

  
--##++[[ShipDetail]]
CREATE TABLE TB_HTMS_SHIPDETAIL(
	SHIPDETAILID INTEGER  not null,
	SHIPID INTEGER,
	CADDRID INTEGER,
	CODETAILID INTEGER,
	PRODUCTID INTEGER,
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	FETCHTONNUM VARCHAR(30),
	FETCHPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTULFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	SHIPDETAILNOTICE VARCHAR(300),
	SHIPDETAILSTATUS INTEGER,
	CREATETIME VARCHAR(30),
	CREATOR VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_SHIPDETAIL primary key (SHIPDETAILID)
);
--##--[[ShipDetail]]

  
--##++[[TransferDetail]]
CREATE TABLE TB_HTMS_TRANSFERDETAIL(
	TRANSDETAILID INTEGER  not null,
	SHIPDETAILID INTEGER,
	TRANSID INTEGER,
	SHIPID INTEGER,
	CADDRID INTEGER,
	PRODUCTID INTEGER,
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	FETCHTONNUM VARCHAR(30),
	FETCHPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTULFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	TRANSDETAILNOTICE VARCHAR(30),
	TRANSDETAILSTATUS INTEGER,
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_TRANSFERDETAIL primary key (TRANSDETAILID)
);
--##--[[TransferDetail]]

  
--##++[[Transfer]]
CREATE TABLE TB_HTMS_TRANSFER(
	TRANSID INTEGER  not null,
	SHIPID INTEGER,
	LOGISTICSID INTEGER,
	CORDERID INTEGER,
	CUSTOMERID INTEGER,
	SHIPCODE VARCHAR(30),
	APPLYTONNUM VARCHAR(30),
	APPLYPACKNUM VARCHAR(30),
	ACTUALTONNUM VARCHAR(30),
	ACTUALPACKNUM VARCHAR(30),
	PLANFREIGHT VARCHAR(30),
	ACTUALFREIGHT VARCHAR(30),
	FREIGHTUNIT VARCHAR(30),
	SHIPNOTICE VARCHAR(300),
	TRANSSTATUS INTEGER,
	CREATOR VARCHAR(30),
	CREATETIME VARCHAR(30),
	MODIFIER VARCHAR(30),
	MODIFYTIME VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_TRANSFER primary key (TRANSID)
);
--##--[[Transfer]]

  
--##++[[Logistics]]
CREATE TABLE TB_HTMS_LOGISTICS(
	LOGISTICSID INTEGER  not null,
	LOGISTICSNAME VARCHAR(100),
	LOGISTICSCODE VARCHAR(100),
	LOGISTICSADDRESS VARCHAR(300),
	LOGISTICSCONTACTOR VARCHAR(100),
	LOGISTICSTELEPHONE VARCHAR(30),
	ISVALIDATE INTEGER default '1',
	constraint PK_TB_HTMS_LOGISTICS primary key (LOGISTICSID)
);
--##--[[Logistics]]

