insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (2, 1, '1101', '市辖区', 2, '', 1, '', '', '11', 0, '11', '北京市', 1);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (300, 1, '1102', '县', 2, '', 1, '', '', '11', 0, '11', '北京市', 1);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (339, 338, '1201', '市辖区', 2, '', 1, '', '', '12', 0, '12', '天津市', 338);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (569, 338, '1202', '市辖县', 2, '', 1, '', '', '12', 0, '12', '天津市', 338);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (637, 636, '1301', '石家庄市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (936, 636, '1302', '唐山市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (1188, 636, '1303', '秦皇岛市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (1291, 636, '1304', '邯郸市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (1554, 636, '1305', '邢台市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (1772, 636, '1306', '保定市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (2142, 636, '1307', '张家口市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (2400, 636, '1308', '承德市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (2629, 636, '1309', '沧州市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (2849, 636, '1310', '廊坊市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (2968, 636, '1311', '衡水市', 2, '', 1, '', '', '13', 0, '13', '河北省', 636);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3103, 3102, '1401', '太原市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3224, 3102, '1402', '大同市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3379, 3102, '1403', '阳泉市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3431, 3102, '1404', '长治市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3597, 3102, '1405', '晋城市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3690, 3102, '1406', '朔州市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3776, 3102, '1407', '晋中市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (3925, 3102, '1408', '运城市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (4093, 3102, '1409', '忻州市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (4304, 3102, '1410', '临汾市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (4494, 3102, '1411', '吕梁市', 2, '', 1, '', '', '14', 0, '14', '山西', 3102);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (4671, 4670, '1501', '呼和浩特市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (4759, 4670, '1502', '包头市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (4849, 4670, '1503', '乌海市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (4874, 4670, '1504', '赤峰市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5029, 4670, '1505', '通辽市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5162, 4670, '1506', '鄂尔多斯市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5236, 4670, '1507', '呼伦贝尔市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5418, 4670, '1508', '巴彦淖尔市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5505, 4670, '1509', '乌兰察布市', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5616, 4670, '1522', '兴安盟', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5702, 4670, '1525', '锡林郭勒盟', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5799, 4670, '1529', '阿拉善盟', 2, '', 1, '', '', '15', 0, '15', '内蒙古自治区', 4670);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (5828, 5827, '2101', '沈阳市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6088, 5827, '2102', '大连市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6266, 5827, '2103', '鞍山市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6384, 5827, '2104', '抚顺市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6476, 5827, '2105', '本溪市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6542, 5827, '2106', '丹东市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6643, 5827, '2107', '锦州市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6771, 5827, '2108', '营口市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6851, 5827, '2109', '阜新市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (6955, 5827, '2110', '辽阳市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7024, 5827, '2111', '盘锦市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7088, 5827, '2112', '铁岭市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7208, 5827, '2113', '朝阳市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7391, 5827, '2114', '葫芦岛市', 2, '', 1, '', '', '21', 0, '21', '辽宁省', 5827);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7532, 7531, '2201', '长春市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7706, 7531, '2202', '吉林市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7868, 7531, '2203', '四平市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (7986, 7531, '2204', '辽源市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (8037, 7531, '2205', '通化市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (8144, 7531, '2206', '白山市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (8216, 7531, '2207', '松原市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (8333, 7531, '2208', '白城市', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (8445, 7531, '2224', '延边朝鲜族自治州', 2, '', 1, '', '', '22', 0, '22', '吉林省', 7531);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (8559, 8558, '2301', '哈尔滨市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (8884, 8558, '2302', '齐齐哈尔市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9117, 8558, '2303', '鸡西市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9222, 8558, '2304', '鹤岗市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9296, 8558, '2305', '双鸭山市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9419, 8558, '2306', '大庆市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9553, 8558, '2307', '伊春市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9785, 8558, '2308', '佳木斯市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9930, 8558, '2309', '七台河市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (9981, 8558, '2310', '牡丹江市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (10084, 8558, '2311', '黑河市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (10252, 8558, '2312', '绥化市', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (10483, 8558, '2327', '大兴安岭地区', 2, '', 1, '', '', '23', 0, '23', '黑龙江省', 8558);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (10544, 10543, '3101', '市辖区', 2, '', 1, '', '', '31', 0, '31', '上海市', 10543);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (10779, 10543, '3102', '县', 2, '', 1, '', '', '31', 0, '31', '上海市', 10543);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (10809, 10808, '3201', '南京市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (10960, 10808, '3202', '无锡市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (11067, 10808, '3203', '徐州市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (11245, 10808, '3204', '常州市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (11348, 10808, '3205', '苏州市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (11482, 10808, '3206', '南通市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (11663, 10808, '3207', '连云港市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (11786, 10808, '3208', '淮安市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (11947, 10808, '3209', '盐城市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (12135, 10808, '3210', '扬州市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (12249, 10808, '3211', '镇江市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (12343, 10808, '3212', '泰州市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (12475, 10808, '3213', '宿迁市', 2, '', 1, '', '', '32', 0, '32', '江苏省', 10808);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (12597, 12596, '3301', '杭州市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (12813, 12596, '3302', '宁波市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (12974, 12596, '3303', '温州市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (13280, 12596, '3304', '嘉兴市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (13364, 12596, '3305', '湖州市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (13437, 12596, '3306', '绍兴市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (13564, 12596, '3307', '金华市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (13726, 12596, '3308', '衢州市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (13840, 12596, '3309', '舟山市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (13890, 12596, '3310', '台州市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14033, 12596, '3311', '丽水市', 2, '', 1, '', '', '33', 0, '33', '浙江省', 12596);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14235, 14234, '3401', '合肥市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14351, 14234, '3402', '芜湖市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14410, 14234, '3403', '蚌埠市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14500, 14234, '3404', '淮南市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14575, 14234, '3405', '马鞍山市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14612, 14234, '3406', '淮北市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14653, 14234, '3407', '铜陵市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14687, 14234, '3408', '安庆市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (14887, 14234, '3410', '黄山市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15005, 14234, '3411', '滁州市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15194, 14234, '3412', '阜阳市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15378, 14234, '3413', '宿州市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15499, 14234, '3414', '巢湖市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15586, 14234, '3415', '六安市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15764, 14234, '3416', '亳州市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15871, 14234, '3417', '池州市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (15958, 14234, '3418', '宣城市', 2, '', 1, '', '', '34', 0, '34', '安徽省', 14234);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (16069, 16068, '3501', '福州市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (16278, 16068, '3502', '厦门市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (16348, 16068, '3503', '莆田市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (16412, 16068, '3504', '三明市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (16572, 16068, '3505', '泉州市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (16754, 16068, '3506', '漳州市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (16924, 16068, '3507', '南平市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17077, 16068, '3508', '龙岩市', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17219, 16068, '3509', '宁德市　', 2, '', 1, '', '', '35', 0, '35', '福建省', 16068);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17360, 17359, '3601', '南昌市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17508, 17359, '3602', '景德镇市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17589, 17359, '3603', '萍乡市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17651, 17359, '3604', '九江市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17894, 17359, '3605', '新余市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17934, 17359, '3606', '鹰潭市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (17999, 17359, '3607', '赣州市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (18330, 17359, '3608', '吉安市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (18598, 17359, '3609', '宜春市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (18829, 17359, '3610', '抚州市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (19024, 17359, '3611', '上饶市', 2, '', 1, '', '', '36', 0, '36', '江西省', 17359);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (19281, 19280, '3701', '济南市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (19421, 19280, '3702', '青岛市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (19608, 19280, '3703', '淄博市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (19724, 19280, '3704', '枣庄市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (19796, 19280, '3705', '东营市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (19846, 19280, '3706', '烟台市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20012, 19280, '3707', '潍坊市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20216, 19280, '3708', '济宁市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20386, 19280, '3709', '泰安市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20480, 19280, '3710', '威海市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20558, 19280, '3711', '日照市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20618, 19280, '3712', '莱芜市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20642, 19280, '3713', '临沂市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20836, 19280, '3714', '德州市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (20981, 19280, '3715', '聊城市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (21123, 19280, '3716', '滨州市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (21218, 19280, '3717', '菏泽市', 2, '', 1, '', '', '37', 0, '37', '山东省', 19280);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (21388, 21387, '4101', '郑州市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (21575, 21387, '4102', '开封市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (21711, 21387, '4103', '洛阳市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (21913, 21387, '4104', '平顶山市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22058, 21387, '4105', '安阳市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22206, 21387, '4106', '鹤壁市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22251, 21387, '4107', '新乡市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22423, 21387, '4108', '焦作市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22558, 21387, '4109', '濮阳市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22655, 21387, '4110', '许昌市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22762, 21387, '4111', '漯河市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22824, 21387, '4112', '三门峡市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (22910, 21387, '4113', '南阳市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (23170, 21387, '4114', '商丘市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (23372, 21387, '4115', '信阳市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (23589, 21387, '4116', '周口市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (23818, 21387, '4117', '驻马店市', 2, '', 1, '', '', '41', 0, '41', '河南省', 21387);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24023, 24022, '4201', '武汉市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24224, 24022, '4202', '黄石市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24291, 24022, '4203', '十堰市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24453, 24022, '4205', '宜昌市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24580, 24022, '4206', '襄樊市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24706, 24022, '4207', '鄂州市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24737, 24022, '4208', '荆门市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24816, 24022, '4209', '孝感市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (24949, 24022, '4210', '荆州市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25086, 24022, '4211', '黄冈市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25249, 24022, '4212', '咸宁市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25335, 24022, '4213', '随州市', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25388, 24022, '4228', '恩施州', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25487, 24022, '4290', '省直辖行政单位', 2, '', 1, '', '', '42', 0, '42', '湖北省', 24022);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25580, 25579, '4301', '长沙市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25758, 25579, '4302', '株洲市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (25912, 25579, '4303', '湘潭市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (26001, 25579, '4304', '衡阳市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (26242, 25579, '4305', '邵阳市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (26485, 25579, '4306', '岳阳市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (26683, 25579, '4307', '常德市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (26925, 25579, '4308', '张家界市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (27038, 25579, '4309', '益阳市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (27147, 25579, '4310', '郴州市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (27418, 25579, '4311', '永州市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (27650, 25579, '4312', '怀化市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (27963, 25579, '4313', '娄底市', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28065, 25579, '4331', '湘西土家族苗族自治州', 2, '', 1, '', '', '43', 0, '43', '湖南省', 25579);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28241, 28240, '4401', '广州市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28421, 28240, '4402', '韶关市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28558, 28240, '4403', '深圳市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28626, 28240, '4404', '珠海市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28659, 28240, '4405', '汕头市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28737, 28240, '4406', '佛山市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28785, 28240, '4407', '江门市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (28880, 28240, '4408', '湛江市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29026, 28240, '4409', '茂名市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29159, 28240, '4412', '肇庆市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29282, 28240, '4413', '惠州市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29371, 28240, '4414', '梅州市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29498, 28240, '4415', '汕尾市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29568, 28240, '4416', '河源市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29679, 28240, '4417', '阳江市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29755, 28240, '4418', '清远市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29855, 28240, '4419', '东莞市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29890, 28240, '4420', '中山市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29915, 28240, '4451', '潮州市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (29977, 28240, '4452', '揭阳市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30086, 28240, '4453', '云浮市', 2, '', 1, '', '', '44', 0, '44', '广东省', 28240);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30165, 30164, '4501', '南宁市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30319, 30164, '4502', '柳州市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30448, 30164, '4503', '桂林市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30613, 30164, '4504', '梧州市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30688, 30164, '4505', '北海市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30724, 30164, '4506', '防城港市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30762, 30164, '4507', '钦州市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30834, 30164, '4508', '贵港市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (30915, 30164, '4509', '玉林市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31033, 30164, '4510', '百色市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31184, 30164, '4511', '贺州市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31249, 30164, '4512', '河池市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31401, 30164, '4513', '来宾市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31478, 30164, '4514', '崇左市', 2, '', 1, '', '', '45', 0, '45', '广西壮族自治区', 30164);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31564, 31563, '4601', '海口市', 2, '', 1, '', '', '46', 0, '46', '海南省', 31563);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31618, 31563, '4602', '三亚市', 2, '', 1, '', '', '46', 0, '46', '海南省', 31563);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31633, 31563, '4690', '省属虚拟市', 2, '', 1, '', '', '46', 0, '46', '海南省', 31563);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (31930, 31929, '5001', '市辖区', 2, '', 1, '', '', '50', 0, '50', '重庆市', 31929);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (32380, 31929, '5002', '县', 2, '', 1, '', '', '50', 0, '50', '重庆市', 31929);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (33008, 33007, '5101', '成都市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (33344, 33007, '5103', '自贡市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (33460, 33007, '5104', '攀枝花市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (33528, 33007, '5105', '泸州市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (33681, 33007, '5106', '德阳市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (33817, 33007, '5107', '绵阳市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (34120, 33007, '5108', '广元市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (34376, 33007, '5109', '遂宁市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (34501, 33007, '5110', '内江市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (34628, 33007, '5111', '乐山市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (34859, 33007, '5113', '南充市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (35288, 33007, '5114', '眉山市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (35427, 33007, '5115', '宜宾市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (35625, 33007, '5116', '广安市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (35813, 33007, '5117', '达州市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (36136, 33007, '5118', '雅安市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (36299, 33007, '5119', '巴中市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (36497, 33007, '5120', '资阳市', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (36679, 33007, '5132', '阿坝州', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (36926, 33007, '5133', '甘孜藏族自治州', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (37270, 33007, '5134', '凉山州', 2, '', 1, '', '', '51', 0, '51', '四川省', 33007);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (37907, 37906, '5201', '贵阳市', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (38042, 37906, '5202', '六盘水市', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (38145, 37906, '5203', '遵义市', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (38402, 37906, '5204', '安顺市', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (38497, 37906, '5222', '铜仁地区', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (38677, 37906, '5223', '黔西南州', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (38816, 37906, '5224', '毕节地区', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (39075, 37906, '5226', '黔东南苗族侗族自治州', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (39302, 37906, '5227', '黔南布依族苗族自治州', 2, '', 1, '', '', '52', 0, '52', '贵州省', 37906);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (39557, 39556, '5301', '昆明市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (39710, 39556, '5303', '曲靖市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (39836, 39556, '5304', '玉溪市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (39923, 39556, '5305', '保山市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40004, 39556, '5306', '昭通市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40160, 39556, '5307', '丽江市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40230, 39556, '5308', '思茅市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40348, 39556, '5309', '临沧市', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40441, 39556, '5323', '楚雄州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40555, 39556, '5325', '红河州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40705, 39556, '5326', '文山州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40816, 39556, '5328', '西双版纳州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40852, 39556, '5329', '大理州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (40979, 39556, '5331', '德宏州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41036, 39556, '5333', '怒江州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41070, 39556, '5334', '迪庆州', 2, '', 1, '', '', '53', 0, '53', '云南省', 39556);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41104, 41103, '5401', '拉萨市', 2, '', 1, '', '', '54', 0, '54', '西藏自治区', 41103);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41178, 41103, '5421', '昌都地区', 2, '', 1, '', '', '54', 0, '54', '西藏自治区', 41103);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41328, 41103, '5422', '山南地区', 2, '', 1, '', '', '54', 0, '54', '西藏自治区', 41103);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41423, 41103, '5423', '日喀则地区', 2, '', 1, '', '', '54', 0, '54', '西藏自治区', 41103);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41645, 41103, '5424', '那曲地区', 2, '', 1, '', '', '54', 0, '54', '西藏自治区', 41103);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41770, 41103, '5425', '阿里地区', 2, '', 1, '', '', '54', 0, '54', '西藏自治区', 41103);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41814, 41103, '5426', '林芝地区', 2, '', 1, '', '', '54', 0, '54', '西藏自治区', 41103);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (41878, 41877, '6101', '西安市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (42069, 41877, '6102', '铜川市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (42119, 41877, '6103', '宝鸡市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (42287, 41877, '6104', '咸阳市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (42490, 41877, '6105', '渭南市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (42703, 41877, '6106', '延安市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (42888, 41877, '6107', '汉中市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (43136, 41877, '6108', '榆林市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (43379, 41877, '6109', '安康市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (43592, 41877, '6110', '商洛市', 2, '', 1, '', '', '61', 0, '61', '陕西省', 41877);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (43777, 43776, '6201', '兰州市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (43904, 43776, '6202', '嘉峪关市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (43914, 43776, '6203', '金昌市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (43936, 43776, '6204', '白银市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44022, 43776, '6205', '天水市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44154, 43776, '6206', '武威市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44265, 43776, '6207', '张掖市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44352, 43776, '6208', '平凉市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44477, 43776, '6209', '酒泉市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44569, 43776, '6210', '庆阳市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44699, 43776, '6211', '定西市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (44829, 43776, '6212', '陇南市', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45035, 43776, '6229', '临夏州', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45174, 43776, '6230', '甘南州', 2, '', 1, '', '', '62', 0, '62', '甘肃省', 43776);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45287, 45286, '6301', '西宁市', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45368, 45286, '6321', '海东地区', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45471, 45286, '6322', '海北州', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45510, 45286, '6323', '黄南州', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45548, 45286, '6325', '海南州', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45597, 45286, '6326', '果洛州', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45648, 45286, '6327', '玉树州', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45701, 45286, '6328', '海西州', 2, '', 1, '', '', '63', 0, '63', '青海省', 45286);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45754, 45753, '6401', '银川市', 2, '', 1, '', '', '64', 0, '64', '宁夏回族自治区', 45753);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45825, 45753, '6402', '石嘴山市', 2, '', 1, '', '', '64', 0, '64', '宁夏回族自治区', 45753);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45871, 45753, '6403', '吴忠市', 2, '', 1, '', '', '64', 0, '64', '宁夏回族自治区', 45753);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45926, 45753, '6404', '固原市', 2, '', 1, '', '', '64', 0, '64', '宁夏回族自治区', 45753);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (45999, 45753, '6405', '中卫市', 2, '', 1, '', '', '64', 0, '64', '宁夏回族自治区', 45753);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46048, 46047, '6501', '乌鲁木齐市', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46138, 46047, '6502', '克拉玛依市', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46162, 46047, '6521', '吐鲁番地区', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46197, 46047, '6522', '哈密地区', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46255, 46047, '6523', '昌吉州', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46380, 46047, '6527', '博尔塔拉蒙古自治州', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46422, 46047, '6528', '巴音郭楞蒙古自治州', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46551, 46047, '6529', '阿克苏地区', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46688, 46047, '6530', '克州', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46747, 46047, '6531', '喀什地区', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (46957, 46047, '6532', '和田地区', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (47069, 46047, '6540', '伊犁州', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (47241, 46047, '6542', '塔城地区', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (47374, 46047, '6543', '阿勒泰地区', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

insert into tb_htms_area002 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF, PROVINCECODE, PROVINCENAME, PROVINCEID)
values (47450, 46047, '6590', '省直辖行政单位', 2, '', 1, '', '', '65', 0, '65', '新疆维吾尔自治区', 46047);

