insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (1, 0, '11', '北京市', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (338, 0, '12', '天津市', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (636, 0, '13', '河北省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (3102, 0, '14', '山西', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (4670, 0, '15', '内蒙古自治区', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (5827, 0, '21', '辽宁省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (7531, 0, '22', '吉林省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (8558, 0, '23', '黑龙江省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (10543, 0, '31', '上海市', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (10808, 0, '32', '江苏省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (12596, 0, '33', '浙江省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (14234, 0, '34', '安徽省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (16068, 0, '35', '福建省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (17359, 0, '36', '江西省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (19280, 0, '37', '山东省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (21387, 0, '41', '河南省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (24022, 0, '42', '湖北省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (25579, 0, '43', '湖南省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (28240, 0, '44', '广东省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (30164, 0, '45', '广西壮族自治区', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (31563, 0, '46', '海南省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (31929, 0, '50', '重庆市', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (33007, 0, '51', '四川省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (37906, 0, '52', '贵州省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (39556, 0, '53', '云南省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (41103, 0, '54', '西藏自治区', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (41877, 0, '61', '陕西省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (43776, 0, '62', '甘肃省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (45286, 0, '63', '青海省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (45753, 0, '64', '宁夏回族自治区', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (46047, 0, '65', '新疆维吾尔自治区', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (47493, 0, '71', '台湾省', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (47494, 0, '81', '香港特别行政区', 1, '', 1, '', '', '0', 0);

insert into tb_htms_area001 (AREAID, PARENTAREAID, AREACODE, AREANAME, AREALEVEL, AREAROUTE, ISVALIDATE, AREALONGTITUE, AREALATITUE, AREAPARENTCODE, ISLEAF)
values (47495, 0, '82', '澳门特别行政区', 1, '', 1, '', '', '0', 0);

