delete from tb_htms_transportsend  ;
delete from tb_htms_senddetail     ;
delete from tb_htms_send           ;
delete from tb_htms_vehicle        ;
delete from tb_htms_driver         ;
delete from tb_htms_transportdetail;
delete from tb_htms_transport      ;
delete from tb_htms_transferdetail ;
delete from tb_htms_transfer       ;
delete from tb_htms_shipdetail     ;
delete from tb_htms_ship           ;
delete from tb_htms_custorderdetail;
delete from tb_htms_custorder      ;
delete from tb_htms_system_log     ;   
delete from tb_htms_carrier;
delete from tb_htms_customeraddr;
delete from tb_htms_customer;
delete from tb_htms_customer_price;
delete from tb_htms_factory;
delete from tb_htms_logistics;
delete from tb_htms_ordersyn;
delete from tb_htms_product;
delete from tb_htms_producttype;
delete from tb_htms_route;
delete from tb_htms_system_log;
commit;
